name: Run Lint, Type Checks, and Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - run: npm run checks
